### ISSUE TITLE
Delete or update "Linux-Development" branch

### ISSUE THREAD

**Issue by Dan9er** [Drewol/unnamed-sdvx-clone#13]
The `Linux-Development` branch is 100 commits behind guusw. I don't think it's of much use anymore since the exe is C/C++ (It can already be run on Linux. Only C*#* is Windows only right now). Either delete it or push from guusw to bring it up to date.

**Comment by jerwuqu** [comment]
That's not how any of that works.

Just because the exe was made using C/C++ does not imply it will work on Linux. In fact, it won't.
Building for linux is similar, but not the same.

@Drewol mentioned that linux builds are broken for the moment (about a week ago), but I'm sure he intends to fix that eventually.
As for the branch itself, I'm not sure if it's in use since I assume linux build-files would be on the same branch as everything else.

**Comment by Dan9er** [comment]
@Drewol, what do you think?

**Comment by Dan9er** [comment]
...what @Drewol meant to say is "Deleted".

(PS. check your Discord DMs)
