### ISSUE TITLE
Bug when using not default input language

### ISSUE THREAD

**Issue by ghost** [Drewol/unnamed-sdvx-clone#135]
With English: ![english-2018 11 19](https://user-images.githubusercontent.com/25438100/48678445-8abb0680-eb94-11e8-80cd-10247a0cd338.png)

With Russian: ![russian-2018 11 19](https://user-images.githubusercontent.com/25438100/48678448-94dd0500-eb94-11e8-9724-8b71fe8ed57e.png)
To be clearer - if I have Russian input on I can't play because the game doesn't recognize my key as key, selected in settings (as can be seen on screenshot above I use comma for right FX, but the game thinks I press 'б' (?), but with other keys, 'ы', for example, it still thinks I press 's', which is okay)

This only applies for some keys (хъжэбю), which can be seen in this highlight, although others seem to be okay (photo from internet):
![kbd1](https://user-images.githubusercontent.com/25438100/48678515-6d3a6c80-eb95-11e8-8cf8-239f8a425a37.jpg)

**Edit**: Oh, and also, these Russian characters displays as '?', which isn't cool, too

**Comment by 123jimin** [comment]
This is caused by `Graphics::Window_Impl::HandleKeyEvent` getting `SDL_Keycode` as opposed to `SDL_Scancode` as the argument for keyboard input.

Since this problem annoys me too, I'll try to create a PR changing the argument into `SDL_Scancode` or `SDL_Keysym` (which itself is simple, but side effects must be carefully examined and averted).
