### ISSUE TITLE
Would a switch port be possible?

### ISSUE THREAD

**Issue by lavaJockey** [Drewol/unnamed-sdvx-clone#287]
I have been looking at the libs the program needed and devkitpro for the switch has the same libs (except libarchive) as it.

**Comment by Hinara** [comment]
Libarchive should not be a problem I think, however this is introducing a new toolochain to the project to check, and to tell you the truth, I don't even know if it will correctly work because is there a way to have a debug mode on the switch (without putting an other OS on it).
And if we do so we will also have to maintain it, which can be hard sometimes especially if you need to do manipulation to get it on the switch.
So short answer: Not until we know how to do it easily with not that much change in the code if possible.

**Comment by lavaJockey** [comment]
I know that a separate branch will mostly be used if it will be possible. But besides that I have seen multiple c++ projects for pc and linux ported to the switch. I know that they are not entirely similar to USC but it can give some help and encouragement. An example is GZDOOM: https://github.com/fgsfdsfgs/gzdoom/tree/switch. It mostly is made up of c++ and multiple libs with some same as USC.

**Comment by Hinara** [comment]
The problem is that even if we develop USC for the switch, the only way to get it on the switch is:
- Switch dev kit (which is really hard to get and cost ~500$ as I've seen on the internet)
- Homebrew (which I'm not entirely sure that this is legal, maybe the homebrew is but the manipulation to get it on the switch might be not, and not a lot of people have homebrew on them switch reducing even more the interest to port it to the switch)

**Comment by lavaJockey** [comment]
I was mostly heading towards the homebrew way because buying a dev kit for the switch would be really expensive. Also getting homebrew on the switch isn't hard to do now a days considering almost all switches can do it. Also for debugging if using homebrew, you can use emulators like yuzu: https://github.com/yuzu-emu/yuzu or Ryujinx: https://github.com/Ryujinx/Ryujinx

**Comment by lavaJockey** [comment]
If you think it isn't a good idea for the official creators like you, I can always fork it and see what I can do with it. I was just wondering if the creators were up for it or not.

**Comment by Melon-Bread** [comment]
>     * Homebrew (which I'm not entirely sure that this is legal, maybe the homebrew is but the manipulation to get it on the switch might be not, and not a lot of people have homebrew on them switch reducing even more the interest to port it to the switch)
> 
> 
> Pls Correct me if I'm wrong

Homebrew is at the point on the switch where development,installation, and application running are done within legal means. No code from Nintendo is used and it is all opensource

**Comment by Drewol** [comment]
While most likely technically possible, it's not something that I want to spend time on as I don't want to homebrew my switch and I also don't think it'll be worth the effort required.

**Comment by lavaJockey** [comment]
@Drewol 

> Also for debugging if using homebrew, you can use emulators like yuzu: https://github.com/yuzu-emu/yuzu or Ryujinx: https://github.com/Ryujinx/Ryujinx
