### ISSUE TITLE
[Bug] Notes appear late

### ISSUE THREAD

**Issue by farkasma** [Drewol/unnamed-sdvx-clone#549]
**Describe the bug**
After updating, notes appear too late, about halfway down the lane. Lasers are not affected.

**Expected behavior**
Notes should be visible from the top of the lane, as usual.

**Screenshots**
https://streamable.com/cjlnj5

**Desktop (please complete the following information):**
 - OS: Linux 5.15.12-1
 - GPU: Intel UHD Graphics 620
 - CPU: Intel Core i5-8250U
 - Version: 7eb260f

**Comment by 123jimin** [comment]
I can't reproduce the bug on 7eb260f2, which is weird...

While I'm not sure about it, I think that 81e85d6 would fix it.
You can test it by following these steps:
1. Backup your `usc-game.exe` by copying it to somewhere else.
2. Download "Game" under the "Artifacts" list in https://github.com/123jimin/unnamed-sdvx-clone/actions/runs/1685727559
3. Overwrite `usc-game.exe` to the one from the archive downloaded from step 2.
4. Execute the game and check whether the bug is fixed.
5. After testing, restore `usc-game.exe`.

If that didn't fix the issue, doing any of these would be helpful for diagnosing the issue.
- (Sanity check) test again for https://github.com/Drewol/unnamed-sdvx-clone/actions/runs/1674445293, by following the same steps
- Check whether it happens for every chart, or for only some of them.
- Check whether it still happens when both the global offset and the song offset is set to 0.
- Press F8 while the bug is happening and take a screenshot (video is fine too but the debug text should be clearly visible).
- Open the log file and see whether all lines starting with `Resetting BeatmapPlayback` are followed by `InitTime = 0, Start = 0` (it should be unless you have entered the practice mode).
- (If you know how) scroll the chart throughout in the practice mode and check whether only a part of the chart is visible.

**Comment by farkasma** [comment]
- Happens on both AppImages
- Happens on all charts I've tested so far
- Happens with offsets at 0
- Debug screenshot: ![Screenshot_20220112_080146](https://user-images.githubusercontent.com/33036336/149080664-a9785b0c-c1ca-4b67-9890-c542ccab6af8.png)
- What level of logging does Resetting BeatmapPlayback need, because I haven't found any lines starting with that.
- Don't know how to manually scroll, but letting maps play to the end shows that it happens for the entirety of the map.

**Comment by farkasma** [comment]
Okay, set logging to debug, now I got some.
Played 2 maps, did not change to practice mode. I got 4 lines, two of them do have `InitTime = 0, Start = 0` the other two have a negative number at `InitTime`. They are also alternating, so one normal, then one negative.

**Comment by 123jimin** [comment]
Currently I have no idea what's causing the problem (especially since it works well on Windows; it might be a compiler-dependent issue I presume), so it might take some time to fix... :(

Meantime you may use the binary from the following path:
https://github.com/Drewol/unnamed-sdvx-clone/actions/runs/1491670932

**Comment by farkasma** [comment]
Would you want to look at my compiler logs?

**Comment by 123jimin** [comment]
The compilation log can be also seen on the action page, so I don't need it.
(However, if your log contains suspicious warnings for files under `Main` or `Beatmap` directory, that would be a hint.)

Currently the biggest mystery is that the bug is not consistently replicated; while I can't run USC on Linux, three other people tried to replicate the bug, and only one person has succeeded replicating the bug.

I think that I need to create a build with detailed logs to investigate into this bug further...

**Comment by Drewol** [comment]
I managed to replicate a similar but not identical issue on my laptop where it appeared to use some of the Hidden/Sudden settings even though it's not supposed to, so try messing with those settings and see if it changes any behavior.

**Comment by 123jimin** [comment]
I added quite a few more information on the debug HUD so that many vital informations related to beatmap playback are visible.
https://github.com/123jimin/unnamed-sdvx-clone/actions/runs/1698715834

Either a screenshot or a video recording (where texts are clearly visible) would be very helpful for diagnosing the issue, especially with following settings:
- No hidden/sudden, default skin
- MMod speed under 300
- Playing a simple chart, such as the NOV chart from here: https://ksm.dev/songs/f5fcee60-a31a-11ea-9b78-9b4b93aa67f5

**Comment by farkasma** [comment]
So uhhhh... Went to get you a screenshot, went back to check hidden/sudden values, and this happened: https://streamable.com/3283lz
And now the game just straight works, both on the AppImage from your repo and the binary I compiled from main. Here's your screenshot anyway.
![Screenshot_20220114_184316](https://user-images.githubusercontent.com/33036336/149561377-0a0fd383-8862-47a0-88f7-21c07def0530.png)
My confusion only grows.

**Comment by 123jimin** [comment]
Oh, I can reproduce the strange behavior of the hid/sud setting on Windows.

**Comment by 123jimin** [comment]
Ah, the cause for that bug is a simple one related to how nuklear works, which is not relevant to this issue.

**Comment by farkasma** [comment]
Okay, I'm a dumbass, and I don't know what mod I'm using, changing to CMod brought to bug back, so I would guess it has something to do with that.

**Comment by 123jimin** [comment]
Thank god I can reproduce the issue
