### ISSUE TITLE
[Bug] Most Songs Crash With Memory Access Error M1 Mac

### ISSUE THREAD

**Issue by Kaz272** [Drewol/unnamed-sdvx-clone#576]
When loading most songs, at certain difficulties, on my M1 Mac USC crashes with Exception Type: EXC_BAD_ACCESS (SIGSEGV)
The song works fine on my Windows installation

1. Select Song _Demetel_ from the SDVX collection
2. Select Level 12 
3. Start the song
4. App Crashes 

**Expected behavior**
The song to play normally

 - OS: MacOS Monterey 12.3
 - GPU/CPU: M1 Pro
 - Version: 0.5.0
 - Git commit: 2022-04-02_81ef5175

**Log file**
Nothing shows as an issue in USC Log files but here is the apple crash log

[USC Crash.txt](https://github.com/Drewol/unnamed-sdvx-clone/files/8465988/USC.Crash.txt)

**Comment by Hinara** [comment]
... So this seems to come from one of the bg/fg shaders there I suppose ?
https://github.com/Hoshikara/LucidWave/blob/master/backgrounds/
Might need to report it to LLVM (of apple I suppose) as it seems to be an abnormal crash... Because it seems to be their compiler crashing when trying to compile the shader code....
The code might be in somewhat invalid, but it should never make their compiler crash

**Comment by Kaz272** [comment]
Yeah, must be from those shaders. I'll go ahead and report it. I appreciate it. Don't know very much about this stuff.
